packages:
  - apps/*
  - packages/*
  - angular-workspace

catalog:
  prettier: ^3.5.3
  zod: ^3.24.1
  '@changesets/cli': ^2.27.10
  verdaccio: ^6.0.2
  lodash-es: 4.17.21
  '@types/lodash-es': 4.17.12
  type-fest: ^4.30.1
  rxjs: ~7.8.0
  tslib: ^2.3.0
  zone.js: ~0.15.0
  husky: ^9.1.7
  lint-staged: ^15.2.11
  'globals': '^15.15.0'
  'sass': '^1.86.0'
  '@faker-js/faker': '9.6.0'

catalogs:
  turbo-latest:
    turbo: ^2.3.3
    '@turbo/gen': ^1.12.4
  typescript-latest:
    typescript: ^5.7.0
    '@types/node': ^22.10.2
  eslint-latest:
    '@typescript-eslint/eslint-plugin': ^8.15.0
    '@typescript-eslint/parser': ^8.15.0
    eslint: ^9.21.0
    eslint-config-prettier: ^10.1.1
    eslint-plugin-only-warn: ^1.1.0
    eslint-plugin-prettier: ^5.2.3
    eslint-plugin-simple-import-sort: ^12.1.1
    eslint-plugin-turbo: ^2.3.0
    typescript-eslint: ^8.24.0
    eslint-plugin-import-x: 4.5.0
    eslint-import-resolver-typescript: 3.7.0
    '@eslint/js': '^9.21.0'
    'eslint-plugin-react-hooks': '^5.1.0'
    'eslint-plugin-react-refresh': '^0.4.19'

  vite-latest:
    vite: ^6.2.0
    vite-plugin-dts: ^4.3.0
    vitest: ^2.1.8
    '@vitest/coverage-v8': ^2.1.8
  angular-latest:
    '@angular/cli': ^19.0.5
    '@angular/compiler-cli': ^19.0.0
    '@angular/animations': ^19.0.0
    '@angular/common': ^19.0.0
    '@angular/compiler': ^19.0.0
    '@angular/core': ^19.0.0
    '@angular/forms': ^19.0.0
    '@angular/platform-browser': ^19.0.0
    '@angular/platform-browser-dynamic': ^19.0.0
    '@angular/router': ^19.0.0
    '@angular-devkit/build-angular': ^19.0.5
    angular-eslint: 19.0.2
    ng-packagr: ^19.0.0
    typescript: 5.6.3
  react-latest:
    'react': '^19.0.0'
    'react-dom': '^19.0.0'
    '@types/react': '^19.0.10'
    '@types/react-dom': '^19.0.4'
    '@vitejs/plugin-react-swc': '^3.8.0'
    '@tanstack/react-table': '^8.21.2'
    '@carbon/react': '^1.78.2'
