packages:
  - apps/*
  - packages/*

catalog:
  prettier: ^3.4.2
  zod: ^3.24.1
  '@changesets/cli': ^2.27.10

catalogs:
  turbo-latest:
    turbo: ^2.3.3
    '@turbo/gen': ^1.12.4
  typescript-latest:
    typescript: ^5.7.0
    '@types/node': ^20.11.24
  eslint-latest:
    '@typescript-eslint/eslint-plugin': ^8.15.0
    '@typescript-eslint/parser': ^8.15.0
    eslint: ^9.15.0
    eslint-config-prettier: ^9.1.0
    eslint-plugin-only-warn: ^1.1.0
    eslint-plugin-prettier: ^5.2.1
    eslint-plugin-simple-import-sort: ^12.1.1
    eslint-plugin-turbo: ^2.3.0
    typescript-eslint: ^8.15.0
  vite-latest:
    vite: ^6.0.1
    vite-plugin-dts: ^4.3.0
    vitest: ^2.1.8
    '@vitest/coverage-v8': ^2.1.8
