packages:
  - apps/*
  - packages/*
  - angular-workspace

catalog:
  '@changesets/cli': ^2.29.7
  '@faker-js/faker': 10.1.0
  '@types/lodash-es': 4.17.12
  globals: 16.5.0
  husky: ^9.1.7
  lint-staged: ^16.2.6
  lodash-es: 4.17.21
  prettier: ^3.6.2
  rxjs: ~7.8.0
  sass: ^1.93.3
  tslib: ^2.8.1
  type-fest: ^5.2.0
  verdaccio: ^6.2.1
  zod: ^4.1.12
  zone.js: ~0.15.0

catalogs:
  angular-latest:
    '@angular-devkit/build-angular': ^20.0.0
    '@angular/animations': ^20.0.0
    '@angular/cli': ^20.0.0
    '@angular/common': ^20.0.0
    '@angular/compiler': ^20.0.0
    '@angular/compiler-cli': ^20.0.0
    '@angular/core': ^20.0.0
    '@angular/forms': ^20.0.0
    '@angular/platform-browser': ^20.0.0
    '@angular/platform-browser-dynamic': ^20.0.0
    '@angular/router': ^20.0.0
    angular-eslint: ^20.0.0
    ng-packagr: ^20.0.0
    typescript: 5.9.3
  eslint-latest:
    '@eslint/js': ^9.39.1
    '@typescript-eslint/eslint-plugin': ^8.46.3
    '@typescript-eslint/parser': ^8.46.3
    eslint: ^9.39.1
    eslint-config-prettier: ^10.1.8
    eslint-import-resolver-typescript: 4.4.4
    eslint-plugin-import-x: 4.16.1
    eslint-plugin-only-warn: ^1.1.0
    eslint-plugin-prettier: ^5.5.4
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.4.24
    eslint-plugin-simple-import-sort: ^12.1.1
    eslint-plugin-turbo: ^2.6.0
    typescript-eslint: ^8.46.3
  react-latest:
    '@tanstack/react-table': ^8.21.3
    '@types/react': ^19.2.2
    '@types/react-dom': ^19.2.2
    '@vitejs/plugin-react-swc': ^4.2.1
    '@vitejs/plugin-react': ^5.0.4
    babel-plugin-react-compiler: ^19.1.0-rc.3
    react: ^19.2.0
    react-dom: ^19.2.0
  carbon-latest:
    '@carbon/react': ^1.95.0
  turbo-latest:
    '@turbo/gen': ^2.6.0
    turbo: ^2.6.0
  typescript-latest:
    '@types/node': ^24.10.0
    typescript: ^5.9.3
  vite-latest:
    '@vitest/coverage-v8': ^4.0.8
    vite: npm:rolldown-vite@7.1.14
    vite-plugin-dts: ^4.5.4
    vitest: ^4.0.8
